"""Paths and tunables. Every value can be overridden with an environment variable."""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[2]
load_dotenv(ROOT / ".env")

CHANNEL_URL = os.getenv("CATALOG_CHANNEL_URL", "https://www.youtube.com/@alheydari")

DATA = Path(os.getenv("CATALOG_DATA_DIR", ROOT / "data"))
CATALOG = DATA / "catalog"  # committed, source of truth
RAW = DATA / "raw"  # gitignored caches (audio, chunks)
SITE_DATA = DATA / "site"  # gitignored, generated by `catalog export`

CHANNEL_FILE = CATALOG / "channel.json"
META_DIR = CATALOG / "meta"
TRANSCRIPT_DIR = CATALOG / "transcripts"
ENRICH_DIR = CATALOG / "enrich"
TAXONOMY_FILE = CATALOG / "taxonomy.json"
ASSIGNMENTS_FILE = CATALOG / "topic_assignments.json"
OVERRIDES_FILE = Path(__file__).parent / "overrides.yaml"
GLOSSARY_FILE = Path(__file__).parent / "glossary.yaml"
AUDIO_DIR = RAW / "audio"
CHUNK_DIR = RAW / "chunks"

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
# Models from best to worst. Every stage tries them in this order, records which one answered,
# and later upgrades results from lower-ranked models when better ones have quota again.
# Models not listed are never called; results from unlisted models rank below all listed ones.
MODEL_RANKING = [
    m.strip()
    for m in os.getenv(
        "CATALOG_MODEL_RANKING",
        "gemini-3.8-flash,gemini-3.5-flash,gemini-3-flash-preview,gemini-3.5-flash-lite",
    ).split(",")
    if m.strip()
]
# Preferred for the one-off taxonomy design call; falls back along MODEL_RANKING.
TAXONOMY_MODEL = os.getenv("CATALOG_TAXONOMY_MODEL", "gemini-3.1-pro-preview")

# Audio is cut into chunks of roughly this many seconds, at the nearest silence.
CHUNK_SECONDS = int(os.getenv("CATALOG_CHUNK_SECONDS", "720"))
# Minimum delay between Gemini requests (free-tier friendly).
GEMINI_MIN_INTERVAL = float(os.getenv("CATALOG_GEMINI_MIN_INTERVAL", "4"))
YTDLP_SLEEP = float(os.getenv("CATALOG_YTDLP_SLEEP", "1.5"))
YTDLP_COOKIES = os.getenv("CATALOG_YTDLP_COOKIES", "")
PLAYLISTS_EN_FILE = CATALOG / "playlists_en.json"
ATTEMPTS_FILE = CATALOG / "attempts.jsonl"  # every chunk translation attempt and its outcome
REVIEW_FILE = CATALOG / "review.json"  # manual review decisions
