"""Paths and tunables. Every value can be overridden with an environment variable."""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[2]
load_dotenv(ROOT / ".env")

CHANNEL_URL = os.getenv("CATALOG_CHANNEL_URL", "https://www.youtube.com/@alheydari")

DATA = Path(os.getenv("CATALOG_DATA_DIR", ROOT / "data"))
CATALOG = DATA / "catalog"  # committed, source of truth
RAW = DATA / "raw"  # gitignored caches (audio, chunks)
SITE_DATA = DATA / "site"  # gitignored, generated by `catalog export`

CHANNEL_FILE = CATALOG / "channel.json"
META_DIR = CATALOG / "meta"
TRANSCRIPT_DIR = CATALOG / "transcripts"
ENRICH_DIR = CATALOG / "enrich"
TAXONOMY_FILE = CATALOG / "taxonomy.json"
ASSIGNMENTS_FILE = CATALOG / "topic_assignments.json"
OVERRIDES_FILE = Path(__file__).parent / "overrides.yaml"
GLOSSARY_FILE = Path(__file__).parent / "glossary.yaml"
AUDIO_DIR = RAW / "audio"
CHUNK_DIR = RAW / "chunks"

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
TRANSCRIBE_MODEL = os.getenv("CATALOG_TRANSCRIBE_MODEL", "gemini-3.8-flash")
ENRICH_MODEL = os.getenv("CATALOG_ENRICH_MODEL", "gemini-3.8-flash")
FALLBACK_MODELS = [
    m.strip()
    for m in os.getenv(
        "CATALOG_FALLBACK_MODELS",
        "gemini-3.7-flash,gemini-3.6-flash,gemini-3.5-flash,gemini-3-flash-preview",
    ).split(",")
    if m.strip()
]
# Metadata-only cataloguing is simple; cheaper "lite" models are acceptable fallbacks there.
ENRICH_FALLBACK_MODELS = [
    m.strip()
    for m in os.getenv(
        "CATALOG_ENRICH_FALLBACK_MODELS",
        ",".join(
            [
                *FALLBACK_MODELS,
                "gemini-3.5-flash-lite",
                "gemini-3.1-flash-lite",
                "gemini-2.5-flash-lite",
            ]
        ),
    ).split(",")
    if m.strip()
]
TAXONOMY_MODEL = os.getenv("CATALOG_TAXONOMY_MODEL", "gemini-3.1-pro-preview")

# Audio is cut into chunks of roughly this many seconds, at the nearest silence.
CHUNK_SECONDS = int(os.getenv("CATALOG_CHUNK_SECONDS", "720"))
# Minimum delay between Gemini requests (free-tier friendly).
GEMINI_MIN_INTERVAL = float(os.getenv("CATALOG_GEMINI_MIN_INTERVAL", "4"))
YTDLP_SLEEP = float(os.getenv("CATALOG_YTDLP_SLEEP", "1.5"))
YTDLP_COOKIES = os.getenv("CATALOG_YTDLP_COOKIES", "")
PLAYLISTS_EN_FILE = CATALOG / "playlists_en.json"
